version: '3'

services:
  redis:
    image: 'redis:latest'
  python_netapp:
    image: python_netapp
    container_name: python_netapp
    build:
      context: ./pythonnetapp
    volumes:
      - ./pythonnetapp:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
  web_netapp:
    image: web_netapp
    container_name: web_netapp
    build:
      context: ./webnetapp
    ports:
      - 80:80